### ISSUE TITLE
Delet Dis Shit

### ISSUE THREAD

**Issue by LordBonzi** [KibiiTV/otakoapp-website#1]
Anime was a mistake
Yara was a failure
Trump will make America great again
Deus Vult Infidel
Bin is a faggot-desu

**Comment by apap04** [comment]
nice 
shit
post

**Comment by Masterflame11** [comment]
God damn bin is an idiot.

**Comment by Masterflame11** [comment]
When you have a server that has over 3000+ members and tell everyone in the server to call b1nzy, one of the worst staff for Discord, "gay" you're gonna get banned. It will happen anywhere. You're disrespecting staff.
